states_prem = [
    {'code': 'AL', 'name': 'Alabama'}, 
    {'code': 'АК', 'name': 'Alaska'}, 
    {'code': 'AZ', 'name': 'Arizona'}, 
    {'code': 'AR', 'name': 'Arkansas'}, 
    {'code': 'CA', 'name': 'California'}, 
    {'code': 'CO', 'name': 'Colorado'}, 
    {'code': 'CT', 'name': 'Connecticut'}, 
    {'code': 'DE', 'name': 'Delaware'}, 
    {'code': 'DC', 'name': 'District of Columbia'}, 
    {'code': 'FL', 'name': 'Florida'}, 
    {'code': 'GA', 'name': 'Georgia'}, 
    {'code': 'HI', 'name': 'Hawaii'}, 
    {'code': 'ID', 'name': 'Idaho'}, 
    {'code': 'IL', 'name': 'Illinois'}, 
    {'code': 'IN', 'name': 'Indiana'}, 
    {'code': 'IA', 'name': 'Iowa'}, 
    {'code': 'KS', 'name': 'Kansas'}, 
    {'code': 'KY', 'name': 'Kentucky'}, 
    {'code': 'LA', 'name': 'Louisiana'}, 
    {'code': 'ME', 'name': 'Maine'}, 
    {'code': 'MD', 'name': 'Maryland'}, 
    {'code': 'МА', 'name': 'Massachusetts'}, 
    {'code': 'MI', 'name': 'Michigan'}, 
    {'code': 'MN', 'name': 'Minnesota'}, 
    {'code': 'MS', 'name': 'Mississippi'}, 
    {'code': 'МО', 'name': 'Missouri'}, 
    {'code': 'MT', 'name': 'Montana'}, 
    {'code': 'NE', 'name': 'Nebraska'}, 
    {'code': 'NV', 'name': 'Nevada'}, 
    {'code': 'NH', 'name': 'New Hampshire'}, 
    {'code': 'NJ', 'name': 'New Jersey'}, 
    {'code': 'NM', 'name': 'New Mexico'}, 
    {'code': 'NY', 'name': 'New York'}, 
    {'code': 'NC', 'name': 'North Carolina'}, 
    {'code': 'ND', 'name': 'North Dakota'}, 
    {'code': 'ОН', 'name': 'Ohio'}, 
    {'code': 'ОК', 'name': 'Oklahoma'}, 
    {'code': 'OR', 'name': 'Oregon'}, 
    {'code': 'РА', 'name': 'Pennsylvania'}, 
    {'code': 'RI', 'name': 'Rhode Island'}, 
    {'code': 'SC', 'name': 'South Carolina'}, 
    {'code': 'SD', 'name': 'South Dakota'}, 
    {'code': 'TN', 'name': 'Tennessee'}, 
    {'code': 'ТХ', 'name': 'Texas'}, 
    {'code': 'UT', 'name': 'Utah'}, 
    {'code': 'VT', 'name': 'Vermont'}, 
    {'code': 'VA', 'name': 'Virginia'}, 
    {'code': 'WA', 'name': 'Washington'}, 
    {'code': 'WV', 'name': 'West Virginia'}, 
    {'code': 'WI', 'name': 'Wisconsin'}, 
    {'code': 'WY', 'name': 'Wyoming'}
]

CC = [{'cc': 'North America', 'regions': ['Greenland',
                                            'Canada',
                                            'United States',
                                            'Mexico',
                                            'Honduras',
                                            'Dominican Republic',
                                            'Jamaica', 'Bahamas',
                                            'Costa Rica',
                                            'Panama']},
    {'cc': 'South America', 'regions': ['Colombia',
                                        'Venezuela',
                                        'Ecuador',
                                        'Peru',
                                        'Suriname',
                                        'Brazil',
                                        'Bolivia',
                                        'Chile',
                                        'Uruguay',
                                        'Argentina']},
    {'cc': 'Africa', 'regions': ['Tunisia',
                                'Algeria',
                                'Morocco',
                                'Senegal',
                                'Ghana',
                                'Egypt',
                                'Kenya',
                                'South Africa']},
    {'cc': 'Asia', 'regions': ['Saudi Arabia',
                                'Kuwait',
                                'Qatar',
                                'United Arab Emirates',
                                'Oman',
                                'Pakistan',
                                'India',
                                'China',
                                'Thailand',
                                'Vietnam',
                                'Malaysia',
                                'Philippines',
                                'Taiwan',
                                'Republic of Korea',
                                'Japan',
                                'Turkey',
                                'Israel']},
    {'cc': 'Australia', 'regions': ['Australia',
                                    'New Zealand']},
    {'cc': 'Europe', 'regions': ['Norway',
                                'Iceland',
                                'Belarus',
                                'Sweden',
                                'Finland',
                                'Republic of Lithuania',
                                'Denmark',
                                'United Kingdom',
                                'Ireland',
                                'Russia',
                                'Ukraine',
                                'Netherlands',
                                'Germany',
                                'Poland',
                                'Czechia',
                                'Slovak Republic',
                                'Hungary',
                                'Romania',
                                'Bulgaria',
                                'Greece',
                                'Italy',
                                'Bosnia and Herzegovina',
                                'Serbia',
                                'Croatia',
                                'Slovenia',
                                'Austria',
                                'Switzerland',
                                'France',
                                'Belgium',
                                'Spain',
                                'Portugal']}]